- name: Seteup Repo file for NodeJs
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install NodeJS
  ansible.builtin.yum:
    name:
     - nodejs
     - gcc-c++
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Download app code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Clean old app code
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy  app code
  ansible.builtin.copy:
     src: /tmp/catalogue_main/
     dest: /home/roboshop/catalogue/
     remote_src: yes
  become_user:roboshop

- name: Install Catalogue Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

