- name: Download {{COMPONENT}} from Git repo and Extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

