- name: Seteup Repo file for NodeJs
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install NodeJS
  ansible.builtin.yum:
    name:
     - nodejs
     - gcc-c++
    state: installed

- name: Setup Add User and App User
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENT}} Dependencies
  shell: cd/home/roboshop/{{COMPONENT}} && npm install
  become_user: roboshop

- name: configure systemD for {{COMPONENT}}
  ansible.builtin.import_roles:
   name: common
   task_from: systemd